### ISSUE TITLE
queue requirements - try

### ISSUE THREAD

**Issue by karandaftary** [arushiprakash/dequemylife#1]
- Create a robust Queue that can perform the following operations: 
    - [x] enqueue(T item) -> adds item to the end of the queue
    - [x] dequeue() -> returns T. The T will be determined later.
        - [x] IMP: dequeue() must NOT return null. If the queue is Empty -> return string: "queue is empty" 
    - [x] printQueue() -> The type T stored in Queue will have it's own toString() method implemented that can be used to print the queue. Assume you can call this toString() method.
    - [x] size() -> returns the number of elements in the queue

**Comment by arushiprakash** [comment]
Done
No tests written since testing framework hasn't been imported
